### ISSUE TITLE
Upgrade to Class Preloader 3.x

### ISSUE THREAD

**Issue by GrahamCampbell** [asgardphp/asgard#6]
Hi, I am the current lead on Class Preloader, and I noticed you're still using 1.x. I'd recommend upgrading to 3.x. Let me know if you need any help with the upgrade. ;)

**Comment by h0gar** [comment]
Thanks for the notice. I have upgraded to classpreloaded 3.

**Comment by GrahamCampbell** [comment]
I'll send a PR.
